# Use Ubuntu 22.04 LTS with Java 21 and Maven 3.x as the base.
image: maven:3.9.6-eclipse-temurin-21-jammy

stages:
- build

maven-build:
  stage: build
  script:
  # Install the 3 needed LTS JDKs that can be used by toolchains
  - apt-get update && apt-get install -y ruby openjdk-8-jdk openjdk-11-jdk openjdk-17-jdk openjdk-21-jdk
  - mkdir -p ${HOME}/.m2 && cp .gitlab/toolchains.xml ${HOME}/.m2/
  # And build it.
  - mvn clean verify
