name: ToolChainsInCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Java and toolchains
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sourcecode
      uses: actions/checkout@v3

    - name: Cache Local Maven Repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup Java 8 (1/2)
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Setup Java 8 (2/2)
      run: echo "JAVA_8=$JAVA_HOME" >> $GITHUB_ENV

    - name: Setup Java 17 (1/2)
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
    - name: Setup Java 17 (2/2)
      run: echo "JAVA_17=$JAVA_HOME" >> $GITHUB_ENV

    # The LAST Java in the list becomes the default (because each overwrites the settings)!
    - name: Setup Java 11 (1/2)
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Setup Java 11 (2/2)
      run: echo "JAVA_11=$JAVA_HOME" >> $GITHUB_ENV

    - name: Create toolchains.xml
      shell: bash
      run: |
        mkdir -p $HOME/.m2 \
        && cat << EOF > $HOME/.m2/toolchains.xml
        <?xml version="1.0" encoding="UTF8"?>
        <toolchains>
            <toolchain>
                <type>jdk</type>
                <provides>
                    <version>8</version>
                </provides>
                <configuration>
                    <jdkHome>${{ env.JAVA_8 }}</jdkHome>
                </configuration>
            </toolchain>
            <toolchain>
                <type>jdk</type>
                <provides>
                    <version>11</version>
                </provides>
                <configuration>
                    <jdkHome>${{ env.JAVA_11 }}</jdkHome>
                </configuration>
            </toolchain>
            <toolchain>
                <type>jdk</type>
                <provides>
                    <version>17</version>
                </provides>
                <configuration>
                    <jdkHome>${{ env.JAVA_17 }}</jdkHome>
                </configuration>
            </toolchain>
        </toolchains>
        EOF

    - name: Verify setup
      shell: bash
      run: |
        echo "Showing currently installed Java versions:";\
        echo "======================================";\
        echo "Default Java"; \
        java -version ; \
        javac -version ; \
        echo JAVA_HOME=${JAVA_HOME} ; \
        echo "======================================";\
        echo "Java 8"; \
        ${{ env.JAVA_8 }}/bin/java -version ; \
        ${{ env.JAVA_8 }}/bin/javac -version ; \
        echo "======================================";\
        echo "Java 11"; \
        ${{ env.JAVA_11 }}/bin/java -version ; \
        ${{ env.JAVA_11 }}/bin/javac -version ; \
        echo "======================================";\
        echo "Java 17"; \
        ${{ env.JAVA_17 }}/bin/java -version ; \
        ${{ env.JAVA_17 }}/bin/javac -version ; \
        echo "======================================";\
        cat $HOME/.m2/toolchains.xml; \
        echo "======================================";

    - name: Build the project
      run: mvn clean verify
